### ISSUE TITLE
CMakeLists.txt still uses org.kde.bitcoin

### ISSUE THREAD

**Issue by z3ntu** [MakG10/plasma-applet-server-status#1]
Messages.sh also still uses some Bitcoin filename
The README.md file has some alt tags still as "Bitcoin Price Plasmoid"

**Comment by MakG10** [comment]
Oops, thanks for noticing. I based it on my last Bitcoin plasmoid and forgot to adjust those files. Fixed.

**Comment by z3ntu** [comment]
Great, thanks for the quick fix.
I have packaged the applet for Arch Linux: https://aur.archlinux.org/packages/plasma5-applets-server-status-git/
Also I would appreciate tagged versions so I can create a non-git / stable package that people can install.

And a quick feedback about the applet: Looks pretty nice and useful (I've configured 3 servers already - physically the same but different website hosts and a general ping to the server). Would it be possible that you show a notification when a server gets unavailable (but maybe check first if the computer has internet or something?) as I might not look at the applet all the time :)

**Comment by z3ntu** [comment]
Oh yeah and a license file is missing so please add one (see https://choosealicense.com/no-license/)

**Comment by MakG10** [comment]
Thanks for pointing that out. I added a release and a license file.

As for the notification feature, it was on my mind, along with showing response time. I will add those features in hopefully nearby future. Thanks for the feedback!

**Comment by z3ntu** [comment]
I'm gonna close this issue as it's solved :) The notification feature request is in #2
